version: '3'
services:
    webserver:
        image: "docker-environment_webserver"
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www/html
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
